version: '3.5'
services:
  redis:
    build: build
    container_name: redis
    ports:
      - 6379:6379
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-expoter
    ports:
      - 9121:9121
    environment:    
      - REDIS_ADDR=redis
      - REDIS_PASSWORD=XXXXXX
