install-compiler:
	@sudo apt install gnucobol

hello:
	cobc -x $@.cob

.PHONY: picture
picture:
	cobc -x $@.cob

.PHONY: value_group
value_group:
	cobc -x $@.cob

.PHONY: accept
accept:
	cobc -x $@.cob
