install-compiler:
	@sudo apt install gnucobol

hello:
	cobc -x $@.cob

.PHONY: picture
picture:
	cobc -x $@.cob


.PHONY: picture2
picture2:
	cobc -x $@.cob	

.PHONY: value_group
value_group:
	cobc -x $@.cob

.PHONY: accept
accept:
	cobc -x $@.cob

.PHONY: move
move:
	cobc -x $@.cob

.PHONY: moveof
moveof:
	cobc -x $@.cob

.PHONY: compute
compute:
	cobc -x $@.cob

.PHONY: strings
strings:
	cobc -x $@.cob

.PHONY: picture_clauses
picture_clauses:
	cobc -x $@.cob